# Generated by Django 2.1.5 on 2019-06-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(default='null', max_length=255)),
                ('article_description', models.CharField(default='null', max_length=255)),
                ('article_addtime', models.DateField()),
                ('article_clicknum', models.IntegerField(default=0)),
                ('article_content', models.TextField()),
                ('article_img', models.CharField(default='null', max_length=9999)),
                ('article_praise_num', models.IntegerField(default='0')),
                ('article_is_recommend', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.CharField(default='', max_length=255)),
                ('comment_addtime', models.DateField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(default='null', max_length=255)),
                ('member_tel', models.CharField(default='null', max_length=11)),
                ('member_email', models.EmailField(max_length=254)),
                ('member_nickname', models.CharField(default='null', max_length=60)),
                ('member_pwd', models.CharField(default='null', max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Praise',
            fields=[
                ('praise_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Article')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('web_id', models.AutoField(primary_key=True, serialize=False)),
                ('web_name', models.CharField(default='null', max_length=255)),
                ('web_content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Member'),
        ),
        migrations.AddField(
            model_name='article',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Member'),
        ),
    ]
