# Generated by Django 2.1.5 on 2019-06-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mesboard',
            fields=[
                ('mesboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('mesboard_name', models.CharField(default='null', max_length=255)),
                ('mesboard_content', models.TextField()),
                ('mesboard_addtime', models.DateField()),
            ],
        ),
    ]
