# Generated by Django 2.1.5 on 2019-07-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_praise_praise_addtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('praise_id', models.AutoField(primary_key=True, serialize=False)),
                ('click_addtime', models.DateField(default=None)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Article')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Member')),
            ],
        ),
    ]
