# Generated by Django 2.1.5 on 2019-06-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='null', max_length=255)),
                ('user_birthday', models.DateField(auto_now_add=True)),
                ('user_work', models.CharField(default='null', max_length=255)),
                ('user_pwd', models.CharField(default='null', max_length=999)),
                ('user_tel', models.CharField(default='null', max_length=11)),
                ('user_is_recommend', models.IntegerField(default='0')),
                ('user_adders', models.CharField(default='null', max_length=150)),
            ],
        ),
    ]
