# Generated by Django 2.1.5 on 2019-06-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_birthday',
            field=models.DateTimeField(),
        ),
    ]
