# Generated by Django 2.1.5 on 2019-07-08 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20190626_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_path', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_pid', models.ForeignKey(blank=True, help_text='父id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='back.Menu', verbose_name='关联的权限')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_name', models.CharField(blank=True, max_length=255, null=True)),
                ('permission_path', models.CharField(blank=True, max_length=255, null=True)),
                ('menu', models.ForeignKey(blank=True, help_text='null表示不是菜单;非null表示是二级菜单', null=True, on_delete=django.db.models.deletion.CASCADE, to='back.Menu', verbose_name='所属菜单')),
                ('permission_pid', models.ForeignKey(blank=True, help_text='父id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='back.Permission', verbose_name='关联的权限')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role_access', models.CharField(blank=True, max_length=255, null=True)),
                ('roleuser', models.ManyToManyField(to='back.Users')),
            ],
        ),
    ]
